---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-svc
spec:
  type: {{ .Values.service.type | default "ClusterIP" | quote }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx-app
    app.kubernetes.io/instance: nginx