---
{{- if eq .Values.serviceAccount.create true | default false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-nginx-sa
  labels:
    app.kubernetes.io/name: nginx-app
    app.kubernetes.io/instance: nginx
{{ end }}